name: iGates
main: com.ptibiscuit.igates.Plugin
version: 0.2
website:
loadbefore: [PluginsBaker]
authors:
- Ptibiscuit
commands:
 igcreate:
  description: Cree un portail.
  usage: /igcreate <Tag> <FillType>
 igset:
  description: Cree un portail.
  usage: /igset ...
 igdelete:
  description: Cree un portail.
  usage: /igdelete ...
 igaddfrom:
  description: Cree un portail.
  usage: /igaddfrom ...
 iglist:
  description: Liste les portails.
  usage: /iglist
 igclearfroms:
  description: ...
  usage: /igclearfroms ...